# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
 
version: '2.1'
 
# Define services
services:
  # App backend service
  air:
    # Configuration for building the docker image for the backend service
    build:
      context: . # Use an image built from the specified dockerfile in the `springboot-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 4000 on the container to port 4000 on the host machine
    restart: always
    depends_on: 
      - mysql-standalone # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/airport?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: alex
      SPRING_DATASOURCE_PASSWORD: pass     
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
 
  # Database Service (Mysql)
  mysql-standalone:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: airport
      MYSQL_USER: alex
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: r00t
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  
 
# Volumes
volumes:
  db-data:
 
# Networks to be created to facilitate communication between containers
networks:
  backend: 